// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWjj0kf7Xx391LeFE7v2mAZDY5s9bJ20',
    appId: '1:290444690195:web:35adb80db676b853bdd0e6',
    messagingSenderId: '290444690195',
    projectId: 'flutter-9a889',
    authDomain: 'flutter-9a889.firebaseapp.com',
    storageBucket: 'flutter-9a889.appspot.com',
    measurementId: 'G-YDBLC5D9V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '*******',
    appId: '1:290444690195:android:b9dec11c66f81d6abdd0e6',
    messagingSenderId: '290444690195',
    projectId: 'flutter-9a889',
    storageBucket: 'flutter-9a889.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNksnnsiZTqMIlso3sfh4GVnCy0P0vMo',
    appId: '1:290444690195:ios:2d85a384c5eb7b5abdd0e6',
    messagingSenderId: '290444690195',
    projectId: 'flutter-9a889',
    storageBucket: 'flutter-9a889.appspot.com',
    iosClientId:
        '290444690195-lsjlslsbtnghl742add8pt57v62r2d8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNksnnsiZTqMIlso3sfh4GVnCy0P0vMo',
    appId: '1:290444690195:ios:2d85a384c5eb7b5abdd0e6',
    messagingSenderId: '290444690195',
    projectId: 'flutter-9a889',
    storageBucket: 'flutter-9a889.appspot.com',
    iosClientId:
        '290444690195-lsjlslsbtnghl742add8pt57v62r2d8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
